export { default as Header } from './Header'
export { default as WhoWeAre } from './WhoWeAre'
export { default as Concepts } from './Concepts'
export { default as SwiperSliderComponent } from './SwiperComponent'
export { default as Portfolio } from './Portfolio'
export { default as Awards } from './Awards'
export { default as Office } from './Office'
export { default as Footer } from './Footer'